### ISSUE TITLE
Given Json object value : '' cannot be clone.

### ISSUE THREAD

**Issue by ryantw** [quarkiverse/quarkus-hibernate-types#64] opened 2022-04-20 21:06 UTC
Hello, this is not an issue with the library, but I am unsure of where to find a solution for my problem.

I am using this library for the JSON type capabilities to persist a java object to a postgres database as jsonb.

I am running in to this error when trying to persist: 

`> java.lang.IllegalArgumentException: The given Json object value: Example{randomuuid='3848a1e8-0694-43f0-a315-9f3c8a09f7c8'} cannot be clone.`

Here is some relevant pseudo-code:

```
@Entity
@TypeDef(name = JsonTypes.JSON_BIN, typeClass = JsonBinaryType.class)
public class Test {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;
    
    @Column(columnDefinition = JsonTypes.JSON_BIN)
    @Type(type = JsonTypes.JSON_BIN)
    private Example example;
}
```

Test & Example are created in a helper class and then example is set with a setter method:

```
Test test = new Test();
Example example = sourceExample;
test.setExample(example);
```

I am trying to understand the error and what I can do to mitigate it, thanks.

**Comment by ryantw** [comment] 2022-04-25 13:27
This can be closed out.

**Comment by wglanzer** [comment] 2022-12-21 16:03
This may be caused by the missing annotation "RegisterForReflection", if running in native mode.
Or there is no no-args-constructor in "Example"?

Just see the example [MyEntity](https://github.com/quarkiverse/quarkus-hibernate-types/blob/main/integration-tests/postgresql/src/main/java/io/quarkiverse/hibernate/types/it/jackson/postgresql/MyEntity.java) and [MyParam](https://github.com/quarkiverse/quarkus-hibernate-types/blob/main/integration-tests/postgresql/src/main/java/io/quarkiverse/hibernate/types/it/jackson/postgresql/MyParam.java), this should be nearly the same.

I will close this issue, because it seems that this is not caused by our extension.

@jmartinspt feel free to open a new issue, if you encounter any other problems (even if they are related to this one).

**Closed by wglanzer** 2022-12-21 16:03 UTC
